
@startuml

    actor Player1 as p1
    actor Player2 as p2

    Rectangle Game {
        left to right direction

        usecase register

        usecase startgame

        usecase checkwinner

        usecase makemove
    }

    makemove --> checkwinner

    p1 -- register
    p1 -- startgame
    p1 -- checkwinner
    p1 -- makemove



@enduml