
@startuml

    actor Player1 as p1
    actor Player2 as p2

    Rectangle Game {
        left to right direction

        usecase register

        usecase startGame

        usecase checkWinner
    }


@enduml